version: "3"
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn build

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    container_name: nginx-exporter
    depends_on:
      - nginx
    ports:
      - "9113:9113"
    command:
      - "-nginx.scrape-uri=http://solcloud-nginx-1:8080/stub_status"
    restart: always

  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"

  mariadb-exporter:
    image: prom/mysqld-exporter:v0.16.0
    environment:
      DATA_SOURCE_NAME: "exporter:password@(solcloud-mariadb-1:3306)/"
    depends_on:
      - mariadb
    ports:
      - "9104:9104"
    command:
      - "--web.listen-address=:9104"
      - "--collect.info_schema.processlist"
      - "--collect.info_schema.innodb_metrics"
      - "--config.my-cnf=/.my.cnf"
    volumes:
      - ./mariadb-exporter/my.cnf:/.my.cnf
    restart: always

volumes:
  mariadb-data:
