version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb-data:
